### PR TITLE
Changing color of onboarding messages doesn't work on updating onboarding stages

### LINKED ISSUE #205: Changing color for default messages does not work
- [x] Add a new message
- [ ] change the color of the stage (via setOnboardingStage)

observe:
- custom messages changed the color
- default (basic) messages still have the old color

### PR DESCRIPTION
**Pull request by dvsilviyageo**
closes #205 

Summary:
* A new message is added to reading in scatterplot.
* On clicking the update reading stage  button. The reading stages icon and color is updated.
* Edited the setOnboardingStage function to check for all the messages to have the all the changes.
* MarkerInformation is also updated.

screencast:

https://user-images.githubusercontent.com/104566246/203790020-1a60e0b6-950f-489c-ae0e-3e0c85a3949b.mp4

### CODE REVIEW

File: packages/core/src/onboarding.ts [hunk 1]
```diff
@@ -153,9 +155,22 @@ export const setOnboardingStage = (stage: Partial<IOnboardingStage>) => {
...
+        newStage = tempStage
         break
       }
     }
+    const tempMessage = get(onboardingMessages).filter(m => m.onboardingStage.id === stage.id)
+    const updateMsg = tempMessage.map((m) => {
+      return {
+        ...m,
+        onboardingStage: newStage
+      }
```
Comment (dvdanielamoitzi) [inline packages/core/src/onboarding.ts:167]: What I actually meant was to return:

```
return {
        ...m,
        onboardingStage: {
          ...m.onboardingStage,
          ...stage
        }
      }
```

File: packages/core/src/onboarding.ts [hunk 2]
```diff
@@ -153,9 +155,22 @@ export const setOnboardingStage = (stage: Partial<IOnboardingStage>) => {
...
+    })
+
+    onboardingMessages.set(updateMsg)
```
Comment (dvdanielamoitzi) [inline packages/core/src/onboarding.ts:170]: As you filtered the onboarding messages on top, you are now deleting all messages form other stages when you only set the updateMsg here

**Review by dvdanielamoitzi — CHANGES_REQUESTED** [review]

**Review by dvdanielamoitzi — APPROVED** [review]
